#!/usr/bin/perl -w
#
# Copyright 2014 (c) Kolbe Kegel
#
# Author: Kolbe Kegel <kolbe@kolbekegel.com>
#
# This file is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the
# Free Software Foundation, version 2.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

use strict;
use Getopt::Std;

# egrep 'Handler_(read|update)' qa/qa_update.log | tr -d '|' | deltas | column -t
# cat global_0508121* | deltas -v | egrep -v '\+0\b' | column -t

# Use -h if you want vertical output, otherwise you get vertical


my %v;
my %opt = (h=>0,v=>0,n=>0);

getopts('hvn', \%opt);

if ($opt{v} and $opt{h}) {
    print STDERR "[ERROR]: -h and -v options conflict.\n";
    exit 1;
}

while (<>) {
    my @F = split(' ');
    push @{$v{$F[0]}}, $F[1]; 
}

sub prn($$) {
    my $n = shift;
    my $v = shift;
    my $p = $n > 0 ? "+" : "";
    printf "%${p}d\t", $v->[$n] - ($n ? $v->[$n-1] : 0), "\t";
}

my @k = sort keys %v;
if ($opt{v}) {
    if ($opt{n}) {
        print "# \t";
        for (my $ln=0; $ln < @{$v{$k[0]}}; $ln++) { printf "%i\t", $ln+1; }
        print "\n";
    }
    for my $k (@k) {
        print "$k\t";
        for (my $n=0; $n < @{$v{$k}}; $n++) {
            prn($n,$v{$k})
        }
        print "\n";
    }
} else {
    my $cols=`tput lines`||40;
    my $ln=0;
    #print "# \t" if $opt{n};
    for (my $n=0; $n < @{$v{$k[0]}}; $n++) { 
        if (not $n % ($cols - 5)) {
            print "#\t" if $opt{n};
            print join("\t", @k),"\n" 
        } 
        printf "%i\t", ++$ln if $opt{n};
        for my $k (@k) { 
            prn($n,$v{$k})
        } 
        print "\n";
    }  
}
